### CSV

In [1]:
import csv
import urllib.request

def extract_csv(url, filename):
    urllib.request.urlretrieve(url, filename)
    with open(filename, "r") as f:
        reader = csv. DictReader(f)
        data = [row for row in reader]
    return data

url = "http://103.146.199.34/dataset/0e036572-f0b1-494a-b4f5-13743417e0b4/resource/0be53431-8e1c-4443-a166-65debfdf19c2/download/kualitas-bayi-desa-simpar-tahun-2019.csv"
filename = "kualitas-bayi-desa-simpar-tahun-2019.csv"
sdm = extract_csv(url, filename)
sdm

[{'Kualitas Bayi Desa Simpar tahun 2019;': 'Jumlah keguguran kandungan ;0 orang'},
 {'Kualitas Bayi Desa Simpar tahun 2019;': 'Jumlah bayi lahir ;40 orang'},
 {'Kualitas Bayi Desa Simpar tahun 2019;': 'Jumlah bayi lahir mati ;0 orang'},
 {'Kualitas Bayi Desa Simpar tahun 2019;': 'Jumlah bayi lahir hidup ;40 orang'},
 {'Kualitas Bayi Desa Simpar tahun 2019;': 'Jumlah bayi mati usia 0 – 1 bulan ;0 orang'},
 {'Kualitas Bayi Desa Simpar tahun 2019;': 'Jumlah bayi mati usia 1 – 12 bulan ;0 orang'},
 {'Kualitas Bayi Desa Simpar tahun 2019;': 'Jumlah bayi lahir berat kurang dari 2',
  None: ['5 kg ;3 orang']},
 {'Kualitas Bayi Desa Simpar tahun 2019;': 'Jumlah bayi 0-5 tahun hidup yang menderita kelainan organ tubuh, fisik dan\nmental ;1 orang'}]

### JSON

In [2]:
import json
import urllib.request

def extract_from_json(url, filename):
    urllib.request.urlretrieve(url, filename)
    with open(filename, "r") as f:
        data = json.load(f)
    return data

url = "https://jsonplaceholder.typicode.com/users"
filename = "users.json"
data_users = extract_from_json(url, filename)
data_users

[{'id': 1,
  'name': 'Leanne Graham',
  'username': 'Bret',
  'email': 'Sincere@april.biz',
  'address': {'street': 'Kulas Light',
   'suite': 'Apt. 556',
   'city': 'Gwenborough',
   'zipcode': '92998-3874',
   'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
  'phone': '1-770-736-8031 x56442',
  'website': 'hildegard.org',
  'company': {'name': 'Romaguera-Crona',
   'catchPhrase': 'Multi-layered client-server neural-net',
   'bs': 'harness real-time e-markets'}},
 {'id': 2,
  'name': 'Ervin Howell',
  'username': 'Antonette',
  'email': 'Shanna@melissa.tv',
  'address': {'street': 'Victor Plains',
   'suite': 'Suite 879',
   'city': 'Wisokyburgh',
   'zipcode': '90566-7771',
   'geo': {'lat': '-43.9509', 'lng': '-34.4618'}},
  'phone': '010-692-6593 x09125',
  'website': 'anastasia.net',
  'company': {'name': 'Deckow-Crist',
   'catchPhrase': 'Proactive didactic contingency',
   'bs': 'synergize scalable supply-chains'}},
 {'id': 3,
  'name': 'Clementine Bauch',
  'username': 'Samantha',
  'email': 'Nathan@yesenia.net',
  'address': {'street': 'Douglas Extension',
   'suite': 'Suite 847',
   'city': 'McKenziehaven',
   'zipcode': '59590-4157',
   'geo': {'lat': '-68.6102', 'lng': '-47.0653'}},
  'phone': '1-463-123-4447',
  'website': 'ramiro.info',
  'company': {'name': 'Romaguera-Jacobson',
   'catchPhrase': 'Face to face bifurcated interface',
   'bs': 'e-enable strategic applications'}},
 {'id': 4,
  'name': 'Patricia Lebsack',
  'username': 'Karianne',
  'email': 'Julianne.OConner@kory.org',
  'address': {'street': 'Hoeger Mall',
   'suite': 'Apt. 692',
   'city': 'South Elvis',
   'zipcode': '53919-4257',
   'geo': {'lat': '29.4572', 'lng': '-164.2990'}},
  'phone': '493-170-9623 x156',
  'website': 'kale.biz',
  'company': {'name': 'Robel-Corkery',
   'catchPhrase': 'Multi-tiered zero tolerance productivity',
   'bs': 'transition cutting-edge web services'}},
 {'id': 5,
  'name': 'Chelsey Dietrich',
  'username': 'Kamren',
  'email': 'Lucio_Hettinger@annie.ca',
  'address': {'street': 'Skiles Walks',
   'suite': 'Suite 351',
   'city': 'Roscoeview',
   'zipcode': '33263',
   'geo': {'lat': '-31.8129', 'lng': '62.5342'}},
  'phone': '(254)954-1289',
  'website': 'demarco.info',
  'company': {'name': 'Keebler LLC',
   'catchPhrase': 'User-centric fault-tolerant solution',
   'bs': 'revolutionize end-to-end systems'}},
 {'id': 6,
  'name': 'Mrs. Dennis Schulist',
  'username': 'Leopoldo_Corkery',
  'email': 'Karley_Dach@jasper.info',
  'address': {'street': 'Norberto Crossing',
   'suite': 'Apt. 950',
   'city': 'South Christy',
   'zipcode': '23505-1337',
   'geo': {'lat': '-71.4197', 'lng': '71.7478'}},
  'phone': '1-477-935-8478 x6430',
  'website': 'ola.org',
  'company': {'name': 'Considine-Lockman',
   'catchPhrase': 'Synchronised bottom-line interface',
   'bs': 'e-enable innovative applications'}},
 {'id': 7,
  'name': 'Kurtis Weissnat',
  'username': 'Elwyn.Skiles',
  'email': 'Telly.Hoeger@billy.biz',
  'address': {'street': 'Rex Trail',
   'suite': 'Suite 280',
   'city': 'Howemouth',
   'zipcode': '58804-1099',
   'geo': {'lat': '24.8918', 'lng': '21.8984'}},
  'phone': '210.067.6132',
  'website': 'elvis.io',
  'company': {'name': 'Johns Group',
   'catchPhrase': 'Configurable multimedia task-force',
   'bs': 'generate enterprise e-tailers'}},
 {'id': 8,
  'name': 'Nicholas Runolfsdottir V',
  'username': 'Maxime_Nienow',
  'email': 'Sherwood@rosamond.me',
  'address': {'street': 'Ellsworth Summit',
   'suite': 'Suite 729',
   'city': 'Aliyaview',
   'zipcode': '45169',
   'geo': {'lat': '-14.3990', 'lng': '-120.7677'}},
  'phone': '586.493.6943 x140',
  'website': 'jacynthe.com',
  'company': {'name': 'Abernathy Group',
   'catchPhrase': 'Implemented secondary concept',
   'bs': 'e-enable extensible e-tailers'}},
 {'id': 9,
  'name': 'Glenna Reichert',
  'username': 'Delphine',
  'email': 'Chaim_McDermott@dana.io',
  'address': {'street': 'Dayna Park',
   'suite': 'Suite 449',
   'city': 'Bartholomebury',
   'zipcode': '76495-3109',
   'geo': {'lat': '24.6463', 'lng': '-168.8889'}},
  'phone': '(775)976-6794 x41206',
  'website': 'conrad.com',
  'company': {'name': 'Yost and Sons',
   'catchPhrase': 'Switchable contextually-based project',
   'bs': 'aggregate real-time technologies'}},
 {'id': 10,
  'name': 'Clementina DuBuque',
  'username': 'Moriah.Stanton',
  'email': 'Rey.Padberg@karina.biz',
  'address': {'street': 'Kattie Turnpike',
   'suite': 'Suite 198',
   'city': 'Lebsackbury',
   'zipcode': '31428-2261',
   'geo': {'lat': '-38.2386', 'lng': '57.2232'}},
  'phone': '024-648-3804',
  'website': 'ambrose.net',
  'company': {'name': 'Hoeger LLC',
   'catchPhrase': 'Centralized empowering task-force',
   'bs': 'target end-to-end models'}}]

### API

In [3]:
import requests

def extract_api(url):
    response = requests.get(url)
    response.raise_for_status()
    data = response.json()
    return data

url = "https://api.open-meteo.com/v1/forecast?latitude=35.6895&longitude=139.6917&current_weather=true"
data_weather = extract_api(url)
data_weather

{'latitude': 35.7,
 'longitude': 139.6875,
 'generationtime_ms': 0.04696846008300781,
 'utc_offset_seconds': 0,
 'timezone': 'GMT',
 'timezone_abbreviation': 'GMT',
 'elevation': 40.0,
 'current_weather_units': {'time': 'iso8601',
  'interval': 'seconds',
  'temperature': '°C',
  'windspeed': 'km/h',
  'winddirection': '°',
  'is_day': '',
  'weathercode': 'wmo code'},
 'current_weather': {'time': '2024-09-03T02:15',
  'interval': 900,
  'temperature': 27.5,
  'windspeed': 10.3,
  'winddirection': 54,
  'is_day': 1,
  'weathercode': 80}}

### WEB

In [4]:
from bs4 import BeautifulSoup
import pandas as pd
import requests

page = requests.get("https://news.republika.co.id/sport")
soup = BeautifulSoup(page.content, 'html.parser')

list_content_item = soup.find("div", {"class": "container-lit"})

list_result_item = []
for each in list_content_item.findAll("li"):
    data = dict()
    data['title'] = each.text.strip()
    data['link'] = each.a.get('href')
    list_result_item.append(data)

pd.DataFrame(list_result_item)

,title,link
0,Sport - 3 jam yang lalu ...,https://news.republika.co.id/berita/sj7jyq348/...
1,Sport - 3 jam yang lalu ...,https://news.republika.co.id/berita/sj7jqb348/...
2,Sport - 4 jam yang lalu ...,https://news.republika.co.id/berita/sj7jcc348/...
3,Sport - 9 jam yang lalu ...,https://news.republika.co.id/berita/sj71is348/...
4,Sport - 12 jam yang lalu ...,https://news.republika.co.id/berita/sj6v3p348/...
5,Sport - 13 jam yang lalu ...,https://news.republika.co.id/berita/sj6sbq348/...
6,Sport - 14 jam yang lalu ...,https://news.republika.co.id/berita/sj6qai348/...
7,Sport - 14 jam yang lalu ...,https://news.republika.co.id/berita/sj6pp9348/...
8,Sport - 18 jam yang lalu ...,https://news.republika.co.id/berita/sj6e5u348/...
9,Sport - 21 jam yang lalu ...,https://news.republika.co.id/berita/sj66c7348/...
10,Sport - 23 jam yang lalu ...,https://news.republika.co.id/berita/sj623i456/...
11,Sport - 23 jam yang lalu ...,https://news.republika.co.id/berita/sj61wi348/...
12,Sport - 23 jam yang lalu ...,https://news.republika.co.id/berita/sj60qw348/...
13,"Sport - 02 September 2024, 09:25 ...",https://news.republika.co.id/berita/sj5yr3348/...
14,"Sport - 02 September 2024, 06:53 ...",https://news.republika.co.id/berita/sj5rpt456/...
15,"Sport - 02 September 2024, 06:36 ...",https://news.republika.co.id/berita/sj5qx2348/...
16,"Sport - 02 September 2024, 06:29 ...",https://news.republika.co.id/berita/sj5qkw348/...
17,"Sport - 02 September 2024, 06:17 ...",https://news.republika.co.id/berita/sj5q1m348/...
18,"Sport - 02 September 2024, 06:09 ...",https://news.republika.co.id/berita/sj5poi348/...
19,"Sport - 02 September 2024, 02:30 ...",https://news.republika.co.id/berita/sj5fj9348/...
20,"Sport - 02 September 2024, 01:41 ...",https://news.republika.co.id/berita/sj5d8h348/...
21,"Sport - 02 September 2024, 01:33 ...",https://news.republika.co.id/berita/sj5cv3348/...
22,"Sport - 02 September 2024, 01:28 ...",https://news.republika.co.id/berita/sj5cmy348/...
23,"Sport - 02 September 2024, 00:43 ...",https://news.republika.co.id/berita/sj5akc348/...
24,"Sport - 02 September 2024, 00:01 ...",https://news.republika.co.id/berita/sj58m6348/...
25,"Sport - 01 September 2024, 22:52 ...",https://news.republika.co.id/berita/sj55fe348/...
26,"Sport - 01 September 2024, 22:26 ...",https://news.republika.co.id/berita/sj5482348/...
27,"Sport - 01 September 2024, 19:48 ...",https://news.republika.co.id/berita/sj4wwl348/...
28,"Sport - 01 September 2024, 18:45 ...",https://news.republika.co.id/berita/sj4tz3348/...
29,"Sport - 01 September 2024, 17:25 ...",https://news.republika.co.id/berita/sj4qae348/...
30,"Sport - 01 September 2024, 17:06 ...",https://news.republika.co.id/berita/sj4oxv348/...
31,"Sport - 01 September 2024, 16:52 ...",https://news.republika.co.id/berita/sj4oqz348/...
32,"Sport - 01 September 2024, 15:16 ...",https://news.republika.co.id/berita/sj4kb3348/...
33,"Sport - 01 September 2024, 14:45 ...",https://news.republika.co.id/berita/sj4iwh348/...
34,"Sport - 01 September 2024, 14:38 ...",https://news.republika.co.id/berita/sj4ikb348/...
35,"Sport - 01 September 2024, 14:26 ...",https://news.republika.co.id/berita/sj4i0p348/...
36,"Sport - 01 September 2024, 09:13 ...",https://news.republika.co.id/berita/sj43i7487/...
37,"Sport - 01 September 2024, 07:49 ...",https://news.republika.co.id/berita/sj3zn5348/...
38,"Sport - 01 September 2024, 07:38 ...",https://news.republika.co.id/berita/sj3z4f348/...
39,"Sport - 01 September 2024, 07:31 ...",https://news.republika.co.id/berita/sj3ysy456/...
40,"Sport - 01 September 2024, 07:17 ...",https://news.republika.co.id/berita/sj3y5p348/...
41,"Sport - 01 September 2024, 06:46 ...",https://news.republika.co.id/berita/sj3wp8348/...
42,"Sport - 01 September 2024, 06:38 ...",https://news.republika.co.id/berita/sj3wck348/...
43,"Sport - 01 September 2024, 06:28 ...",https://news.republika.co.id/berita/sj3vur348/...
44,"Sport - 01 September 2024, 06:14 ...",https://news.republika.co.id/berita/sj3v7c348/...
45,Read More,None

### WEB 2

In [5]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

page = requests.get("https://en.wikipedia.org/wiki/List_of_current_Premier_League_and_English_Football_League_managers")
soup = BeautifulSoup(page.content, 'html.parser')

table = soup.find("table", {"class": "wikitable"})
rows = table.findAll("tr")

row_data = []
for row in rows:
    cell_data = []
    if row.contents[11].get_text() == "Manager": 
        break
    for item in row.findAll(["th", "td"]):
        cell_data.append(item.get_text())
    row_data.append(cell_data)

df_football_managers = pd.DataFrame(row_data)
df_football_managers.columns = df_football_managers.loc[0].str.replace('\n', '')
df_football_managers = df_football_managers[1:]
df_football_managers = df_football_managers.applymap(lambda x: x.replace('\n', ''))
df_football_managers.head()

,Manager,Nation,Date of birth,Club,Division,From,Time as manager,Ref(s)
1,Simon Weaver,England,20 December 1977,Harrogate Town,League Two,21 May 2009,"15 years, 104 days",[6]
2,Pep Guardiola,Spain,18 January 1971,Manchester City,Premier League,1 July 2016,"8 years, 63 days",[7]
3,Mark Robins,England,22 December 1969,Coventry City,Championship,6 March 2017,"7 years, 180 days",[8]
4,Thomas Frank,Denmark,9 October 1973,Brentford,Premier League,16 October 2018,"5 years, 322 days",[9]
5,Mikel Arteta,Spain,26 March 1982,Arsenal,Premier League,22 December 2019,"4 years, 255 days",[10]

### MEMORY

In [6]:
import io
import csv
import requests

def extract_csv_from_memory(url):
    response = requests.get(url)
    content = response.content.decode("utf-8")
    with io.StringIO(content) as f:
        reader = csv.reader(f)
        data = [row for row in reader]
    return data

url = "https://raw.githubusercontent.com/fivethirtyeight/data/master/alcohol-consumption/drinks.csv"
data_drinks = extract_csv_from_memory(url)
data_drinks

[['country',
  'beer_servings',
  'spirit_servings',
  'wine_servings',
  'total_litres_of_pure_alcohol'],
 ['Afghanistan', '0', '0', '0', '0.0'],
 ['Albania', '89', '132', '54', '4.9'],
 ['Algeria', '25', '0', '14', '0.7'],
 ['Andorra', '245', '138', '312', '12.4'],
 ['Angola', '217', '57', '45', '5.9'],
 ['Antigua & Barbuda', '102', '128', '45', '4.9'],
 ['Argentina', '193', '25', '221', '8.3'],
 ['Armenia', '21', '179', '11', '3.8'],
 ['Australia', '261', '72', '212', '10.4'],
 ['Austria', '279', '75', '191', '9.7'],
 ['Azerbaijan', '21', '46', '5', '1.3'],
 ['Bahamas', '122', '176', '51', '6.3'],
 ['Bahrain', '42', '63', '7', '2.0'],
 ['Bangladesh', '0', '0', '0', '0.0'],
 ['Barbados', '143', '173', '36', '6.3'],
 ['Belarus', '142', '373', '42', '14.4'],
 ['Belgium', '295', '84', '212', '10.5'],
 ['Belize', '263', '114', '8', '6.8'],
 ['Benin', '34', '4', '13', '1.1'],
 ['Bhutan', '23', '0', '0', '0.4'],
 ['Bolivia', '167', '41', '8', '3.8'],
 ['Bosnia-Herzegovina', '76', '173', '8', '4.6'],
 ['Botswana', '173', '35', '35', '5.4'],
 ['Brazil', '245', '145', '16', '7.2'],
 ['Brunei', '31', '2', '1', '0.6'],
 ['Bulgaria', '231', '252', '94', '10.3'],
 ['Burkina Faso', '25', '7', '7', '4.3'],
 ['Burundi', '88', '0', '0', '6.3'],
 ["Cote d'Ivoire", '37', '1', '7', '4.0'],
 ['Cabo Verde', '144', '56', '16', '4.0'],
 ['Cambodia', '57', '65', '1', '2.2'],
 ['Cameroon', '147', '1', '4', '5.8'],
 ['Canada', '240', '122', '100', '8.2'],
 ['Central African Republic', '17', '2', '1', '1.8'],
 ['Chad', '15', '1', '1', '0.4'],
 ['Chile', '130', '124', '172', '7.6'],
 ['China', '79', '192', '8', '5.0'],
 ['Colombia', '159', '76', '3', '4.2'],
 ['Comoros', '1', '3', '1', '0.1'],
 ['Congo', '76', '1', '9', '1.7'],
 ['Cook Islands', '0', '254', '74', '5.9'],
 ['Costa Rica', '149', '87', '11', '4.4'],
 ['Croatia', '230', '87', '254', '10.2'],
 ['Cuba', '93', '137', '5', '4.2'],
 ['Cyprus', '192', '154', '113', '8.2'],
 ['Czech Republic', '361', '170', '134', '11.8'],
 ['North Korea', '0', '0', '0', '0.0'],
 ['DR Congo', '32', '3', '1', '2.3'],
 ['Denmark', '224', '81', '278', '10.4'],
 ['Djibouti', '15', '44', '3', '1.1'],
 ['Dominica', '52', '286', '26', '6.6'],
 ['Dominican Republic', '193', '147', '9', '6.2'],
 ['Ecuador', '162', '74', '3', '4.2'],
 ['Egypt', '6', '4', '1', '0.2'],
 ['El Salvador', '52', '69', '2', '2.2'],
 ['Equatorial Guinea', '92', '0', '233', '5.8'],
 ['Eritrea', '18', '0', '0', '0.5'],
 ['Estonia', '224', '194', '59', '9.5'],
 ['Ethiopia', '20', '3', '0', '0.7'],
 ['Fiji', '77', '35', '1', '2.0'],
 ['Finland', '263', '133', '97', '10.0'],
 ['France', '127', '151', '370', '11.8'],
 ['Gabon', '347', '98', '59', '8.9'],
 ['Gambia', '8', '0', '1', '2.4'],
 ['Georgia', '52', '100', '149', '5.4'],
 ['Germany', '346', '117', '175', '11.3'],
 ['Ghana', '31', '3', '10', '1.8'],
 ['Greece', '133', '112', '218', '8.3'],
 ['Grenada', '199', '438', '28', '11.9'],
 ['Guatemala', '53', '69', '2', '2.2'],
 ['Guinea', '9', '0', '2', '0.2'],
 ['Guinea-Bissau', '28', '31', '21', '2.5'],
 ['Guyana', '93', '302', '1', '7.1'],
 ['Haiti', '1', '326', '1', '5.9'],
 ['Honduras', '69', '98', '2', '3.0'],
 ['Hungary', '234', '215', '185', '11.3'],
 ['Iceland', '233', '61', '78', '6.6'],
 ['India', '9', '114', '0', '2.2'],
 ['Indonesia', '5', '1', '0', '0.1'],
 ['Iran', '0', '0', '0', '0.0'],
 ['Iraq', '9', '3', '0', '0.2'],
 ['Ireland', '313', '118', '165', '11.4'],
 ['Israel', '63', '69', '9', '2.5'],
 ['Italy', '85', '42', '237', '6.5'],
 ['Jamaica', '82', '97', '9', '3.4'],
 ['Japan', '77', '202', '16', '7.0'],
 ['Jordan', '6', '21', '1', '0.5'],
 ['Kazakhstan', '124', '246', '12', '6.8'],
 ['Kenya', '58', '22', '2', '1.8'],
 ['Kiribati', '21', '34', '1', '1.0'],
 ['Kuwait', '0', '0', '0', '0.0'],
 ['Kyrgyzstan', '31', '97', '6', '2.4'],
 ['Laos', '62', '0', '123', '6.2'],
 ['Latvia', '281', '216', '62', '10.5'],
 ['Lebanon', '20', '55', '31', '1.9'],
 ['Lesotho', '82', '29', '0', '2.8'],
 ['Liberia', '19', '152', '2', '3.1'],
 ['Libya', '0', '0', '0', '0.0'],
 ['Lithuania', '343', '244', '56', '12.9'],
 ['Luxembourg', '236', '133', '271', '11.4'],
 ['Madagascar', '26', '15', '4', '0.8'],
 ['Malawi', '8', '11', '1', '1.5'],
 ['Malaysia', '13', '4', '0', '0.3'],
 ['Maldives', '0', '0', '0', '0.0'],
 ['Mali', '5', '1', '1', '0.6'],
 ['Malta', '149', '100', '120', '6.6'],
 ['Marshall Islands', '0', '0', '0', '0.0'],
 ['Mauritania', '0', '0', '0', '0.0'],
 ['Mauritius', '98', '31', '18', '2.6'],
 ['Mexico', '238', '68', '5', '5.5'],
 ['Micronesia', '62', '50', '18', '2.3'],
 ['Monaco', '0', '0', '0', '0.0'],
 ['Mongolia', '77', '189', '8', '4.9'],
 ['Montenegro', '31', '114', '128', '4.9'],
 ['Morocco', '12', '6', '10', '0.5'],
 ['Mozambique', '47', '18', '5', '1.3'],
 ['Myanmar', '5', '1', '0', '0.1'],
 ['Namibia', '376', '3', '1', '6.8'],
 ['Nauru', '49', '0', '8', '1.0'],
 ['Nepal', '5', '6', '0', '0.2'],
 ['Netherlands', '251', '88', '190', '9.4'],
 ['New Zealand', '203', '79', '175', '9.3'],
 ['Nicaragua', '78', '118', '1', '3.5'],
 ['Niger', '3', '2', '1', '0.1'],
 ['Nigeria', '42', '5', '2', '9.1'],
 ['Niue', '188', '200', '7', '7.0'],
 ['Norway', '169', '71', '129', '6.7'],
 ['Oman', '22', '16', '1', '0.7'],
 ['Pakistan', '0', '0', '0', '0.0'],
 ['Palau', '306', '63', '23', '6.9'],
 ['Panama', '285', '104', '18', '7.2'],
 ['Papua New Guinea', '44', '39', '1', '1.5'],
 ['Paraguay', '213', '117', '74', '7.3'],
 ['Peru', '163', '160', '21', '6.1'],
 ['Philippines', '71', '186', '1', '4.6'],
 ['Poland', '343', '215', '56', '10.9'],
 ['Portugal', '194', '67', '339', '11.0'],
 ['Qatar', '1', '42', '7', '0.9'],
 ['South Korea', '140', '16', '9', '9.8'],
 ['Moldova', '109', '226', '18', '6.3'],
 ['Romania', '297', '122', '167', '10.4'],
 ['Russian Federation', '247', '326', '73', '11.5'],
 ['Rwanda', '43', '2', '0', '6.8'],
 ['St. Kitts & Nevis', '194', '205', '32', '7.7'],
 ['St. Lucia', '171', '315', '71', '10.1'],
 ['St. Vincent & the Grenadines', '120', '221', '11', '6.3'],
 ['Samoa', '105', '18', '24', '2.6'],
 ['San Marino', '0', '0', '0', '0.0'],
 ['Sao Tome & Principe', '56', '38', '140', '4.2'],
 ['Saudi Arabia', '0', '5', '0', '0.1'],
 ['Senegal', '9', '1', '7', '0.3'],
 ['Serbia', '283', '131', '127', '9.6'],
 ['Seychelles', '157', '25', '51', '4.1'],
 ['Sierra Leone', '25', '3', '2', '6.7'],
 ['Singapore', '60', '12', '11', '1.5'],
 ['Slovakia', '196', '293', '116', '11.4'],
 ['Slovenia', '270', '51', '276', '10.6'],
 ['Solomon Islands', '56', '11', '1', '1.2'],
 ['Somalia', '0', '0', '0', '0.0'],
 ['South Africa', '225', '76', '81', '8.2'],
 ['Spain', '284', '157', '112', '10.0'],
 ['Sri Lanka', '16', '104', '0', '2.2'],
 ['Sudan', '8', '13', '0', '1.7'],
 ['Suriname', '128', '178', '7', '5.6'],
 ['Swaziland', '90', '2', '2', '4.7'],
 ['Sweden', '152', '60', '186', '7.2'],
 ['Switzerland', '185', '100', '280', '10.2'],
 ['Syria', '5', '35', '16', '1.0'],
 ['Tajikistan', '2', '15', '0', '0.3'],
 ['Thailand', '99', '258', '1', '6.4'],
 ['Macedonia', '106', '27', '86', '3.9'],
 ['Timor-Leste', '1', '1', '4', '0.1'],
 ['Togo', '36', '2', '19', '1.3'],
 ['Tonga', '36', '21', '5', '1.1'],
 ['Trinidad & Tobago', '197', '156', '7', '6.4'],
 ['Tunisia', '51', '3', '20', '1.3'],
 ['Turkey', '51', '22', '7', '1.4'],
 ['Turkmenistan', '19', '71', '32', '2.2'],
 ['Tuvalu', '6', '41', '9', '1.0'],
 ['Uganda', '45', '9', '0', '8.3'],
 ['Ukraine', '206', '237', '45', '8.9'],
 ['United Arab Emirates', '16', '135', '5', '2.8'],
 ['United Kingdom', '219', '126', '195', '10.4'],
 ['Tanzania', '36', '6', '1', '5.7'],
 ['USA', '249', '158', '84', '8.7'],
 ['Uruguay', '115', '35', '220', '6.6'],
 ['Uzbekistan', '25', '101', '8', '2.4'],
 ['Vanuatu', '21', '18', '11', '0.9'],
 ['Venezuela', '333', '100', '3', '7.7'],
 ['Vietnam', '111', '2', '1', '2.0'],
 ['Yemen', '6', '0', '0', '0.1'],
 ['Zambia', '32', '19', '4', '2.5'],
 ['Zimbabwe', '64', '18', '4', '4.7']]

### pandas local

In [7]:
import pandas as pd
import urllib.request

pd.options.display.max_columns = None

def extract_json_from_local_with_pandas(url, filename):
    urllib.request.urlretrieve(url, filename)
    df = pd.read_json(filename)
    return df

url = "https://jsonplaceholder.typicode.com/albums"
filename = "albums.json"
df_albums = extract_json_from_local_with_pandas(url, filename)
print(df_albums)

    userId   id                                              title
0        1    1                              quidem molestiae enim
1        1    2                   sunt qui excepturi placeat culpa
2        1    3                                 omnis laborum odio
3        1    4           non esse culpa molestiae omnis sed optio
4        1    5                                  eaque aut omnis a
..     ...  ...                                                ...
95      10   96  unde et ut molestiae est molestias voluptatem ...
96      10   97                                       est quod aut
97      10   98  omnis quia possimus nesciunt deleniti assumend...
98      10   99    consectetur ut id impedit dolores sit ad ex aut
99      10  100                                 enim repellat iste

[100 rows x 3 columns]

### SQLAIchemy

In [8]:
import pandas as pd
import urllib.request
from sqlalchemy import create_engine

pd.options.display.max_columns = None

def extract_sqlite_with_sqlalchemy(url, filename, query):
    urllib.request.urlretrieve(url, filename)
    engine = create_engine(f"sqlite:///{filename}")
    connection = engine.connect().execution_options(stream_results=True)
    df = pd.read_sql(query, connection)
    connection.close()
    engine.dispose()
    return df

url = "https://github.com/djv007/Project-IMDB-database/raw/master/IMDB.sqlite"
filename = "imdb.db"
query = "SELECT * FROM IMDB LIMIT 10" 
df_sqlite = extract_sqlite_with_sqlalchemy(url, filename, query)
print(df_sqlite)

  Movie_id                                              Title  Rating  \
0    36809                            12 Years a Slave (2013)     8.1
1    30114                                   127 Hours (2010)     7.6
2    37367                                       50/50 (2011)     7.7
3    49473                                  About Time (2013)     7.8
4    14867                                       Amour (2012)     7.9
5    33832                                        Argo (2012)     7.7
6    31722                                     Arrival (2016)     8.0
7    25398                             Before Midnight (2013)     7.9
8    10099                                  Big Hero 6 (2014)     7.8
9    25281  Birdman or (The Unexpected Virtue of Ignorance...     7.8

   TotalVotes MetaCritic       Budget  Runtime CVotes10 CVotes09 CVotes08  \
0      496092         96   20000000.0  134 min    75556   126223   161460
1      297075         82   18000000.0   94 min    28939    44110    98845
2      283935         72    8000000.0  100 min    28304    47501    99524
3      225412              12000000.0  123 min    38556    43170    70850
4       76121         94    8900000.0  127 min    11093    15944    22942
5      486840         86   44500000.0  120 min    43875    89490   171495
6      370842         81   47000000.0  116 min    55533    87850   109536
7      106553         94    3000000.0  109 min    16953    22109    31439
8      315485         74  165000000.0             50311    61304   103726
9      448725         88   18000000.0  119 min    60209    94476   121637

  CVotes07 CVotes06 CVotes05 CVotes04 CVotes03 CVotes02 CVotes01 CVotesMale  \
0    83070    27231     9603     4021     2420     1785     4739     313823
1    78451    28394     9403     3796     1930     1161     2059     212866
2    71485    24252     7545     2381     1109      634     1202     188925
3    45487    16542     5673     2210     1084      664     1182     126718
4    14187     5945     2585     1188      710      534      995      49808
5   115165    37332    12630     4992     2910     2020     6941     334838
6    65440    26913    10556     5057     3083     2194     4734     237437
7    19251     8142     3412     1649     1033      826     1745      67076
8    65681    22389     6830     2251     1036      539     1439     187383
9    80828    38373    19161    10116     6750     5378    11807     292808

  CVotesFemale CVotesU18 CVotesU18M CVotesU18F CVotes1829 CVotes1829M  \
0        82012      1837       1363        457     200910      153669
1        44600       745        567        170     133336      106007
2        58348       506        348        153     132350       96269
3        58098       654        325        321      92940       57778
4        16719       121         95         24      28593       20107
5        67910       971        795        162     178794      146371
6        46272      1943       1544        376     126301      101741
7        23823       208        138         66      43312       30016
8        58731      2446       1571        855     128237       91744
9        63310      1891       1538        334     178850      142244

  CVotes1829F CVotes3044 CVotes3044M CVotes3044F CVotes45A CVotes45AM  \
0       45301     138762      112943       23895     29252      23072
1       26152     102120       86609       14304     14895      12400
2       34765      94745       75394       18163     12829       9912
3       34126      67477       50212       16222     13973      10690
4        8167      28691       21990        6269      7425       5803
5       30643     163795      136391       24948     36215      28817
6       23163     111985       95005       15227     24027      20118
7       12857      37072       28401        8189      7479       5891
8       35122      84098       68040       14796     13974      11304
9       34666     129547      108049       19457     26016      21166

  CVotes45AF CVotes1000 CVotesUS CVotesnUS VotesM VotesF VotesU18 VotesU18M  \
0       5726        664    53328  224519.0    8.1    8.1      8.4       8.4
1       2261        649    38478  169745.0    7.6    7.6      7.9       7.9
2       2681        555    46947  147849.0    7.7    7.7      7.9       7.9
3       3026        475    20450  111670.0    7.8    7.9      8.2       8.1
4       1490        391     7959   46138.0    7.8    7.9      8.6       8.7
5       6752        740    70110  229137.0    7.7    7.9      8.0       8.0
6       3440        537    42062  163774.0    7.9    8.0      8.6       8.6
7       1470        447    12382   59116.0    7.9    7.8      8.1       8.3
8       2400        525    36702  131818.0    7.7    8.2      8.2       8.0
9       4329        656    52288  203731.0    7.8    7.5      8.5       8.6

  VotesU18F Votes1829 Votes1829M Votes1829F Votes3044 Votes3044M Votes3044F  \
0       8.5       8.2        8.2        8.2       8.0        7.9        8.0
1       7.9       7.7        7.8        7.7       7.5        7.5        7.5
2       7.9       7.8        7.8        7.7       7.6        7.6        7.6
3       8.3       8.0        8.0        8.0       7.6        7.6        7.7
4       8.5       8.0        8.0        7.9       7.7        7.7        7.9
5       7.8       7.8        7.8        7.9       7.7        7.6        7.8
6       8.4       8.2        8.2        8.1       7.8        7.8        7.8
7       7.4       8.1        8.2        7.9       7.8        7.8        7.6
8       8.7       7.9        7.8        8.3       7.7        7.6        8.0
9       7.9       8.0        8.1        7.7       7.6        7.6        7.3

  Votes45A Votes45AM Votes45AF VotesIMDB Votes1000 VotesUS VotesnUS
0      7.8       7.8       8.1       8.0       7.7     8.3      8.0
1      7.3       7.3       7.5       7.6       7.0     7.7      7.6
2      7.4       7.4       7.5       7.4       7.0     7.9      7.6
3      7.6       7.5       7.8       7.7       6.9     7.8      7.7
4      7.9       7.8       8.1       6.6       7.2     7.9      7.8
5      7.7       7.7       8.0       8.1       7.2     8.0      7.6
6      7.6       7.6       7.7       8.3       7.3     8.0      7.9
7      7.3       7.4       7.2       8.5       7.0     8.0      7.9
8      7.6       7.6       7.9       7.9       7.2     7.9      7.7
9      7.2       7.3       7.0       7.8       7.1     7.9      7.7

### ETL

In [9]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from sqlalchemy import create_engine

def extract_news(url):
    response = requests.get(url)
    response.raise_for_status() 
    soup = BeautifulSoup(response.content, "html.parser")
    data = [h2.get_text() for h2 in soup.find_all("h2")]
    df = pd.DataFrame(data, columns=["title"])
    return df

def load_sqlite(df, table_name, db_path="sqlite:///news.db"):
    engine = create_engine(db_path)
    with engine.connect() as conn:
        df.to_sql(table_name, conn, index=False, if_exists="replace")

def transform_uppercase(df):
    df['title'] = df['title'].str.upper()
    return df

url = "https://edition.cnn.com/world"
table_name = "news"

df_news = extract_news(url)
print("Extract berhasil")
df_news_transformed = transform_uppercase(df_news)
print("Transform berhasil")
load_sqlite(df_news_transformed, table_name)
print("Load berhasil")

Extract berhasil
Transform berhasil
Load berhasil